name: Coding Standards and Static Analysis

on: [ push ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer, cs2pr

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Composer cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles( 'composer.lock' ) }}-${{ hashFiles( '.github/workflows/main.yml' ) }}

      - name: NodeJS cache
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ hashFiles( 'package-lock.json' ) }}-${{ hashFiles( '.github/workflows/main.yml' ) }}

      - name: Install Composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install

      - name: Install NodeJS dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: PHP Coding standards
        run: npm run lint:php

      - name: PHP Static Analysis
        run: npm run static-analysis:php
